use serde::{Deserialize, Serialize};
use std::fs::{self, File};
use std::io::{BufRead, BufReader, Write};
use std::path::Path;
use crate::error::{LauncherError, Result};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AdminUser {
    pub steam_id: String,
    pub role: String, // "owner" or "moderator"
    pub name: String,
    pub notes: String,
}

pub struct AdminManager;

impl AdminManager {
    pub fn get_users_cfg_path(install_path: &Path, identity: &str) -> std::path::PathBuf {
        install_path
            .join("server")
            .join(identity)
            .join("cfg")
            .join("users.cfg")
    }

    pub fn load_admins(install_path: &Path, identity: &str) -> Vec<AdminUser> {
        let path = Self::get_users_cfg_path(install_path, identity);
        if !path.is_file() {
            return Vec::new();
        }

        let mut list = Vec::new();
        if let Ok(file) = File::open(&path) {
            let reader = BufReader::new(file);
            for line_res in reader.lines().flatten() {
                let trimmed = line_res.trim();
                if trimmed.is_empty() || trimmed.starts_with("//") || trimmed.starts_with('#') {
                    continue;
                }

                // Format: <role> <steamid> "<name>" "<notes>"
                // Example: ownerid 76561198000000000 "Admin" "Server Owner"
                let lower = trimmed.to_lowercase();
                let role = if lower.starts_with("ownerid") {
                    "owner"
                } else if lower.starts_with("moderatorid") {
                    "moderator"
                } else {
                    continue;
                };

                let tokens = Self::tokenize_cfg_line(trimmed);
                if tokens.len() >= 2 {
                    let steam_id = tokens[1].clone();
                    let name = tokens.get(2).cloned().unwrap_or_else(|| "Admin".to_string());
                    let notes = tokens.get(3).cloned().unwrap_or_else(|| "".to_string());
                    list.push(AdminUser {
                        steam_id,
                        role: role.to_string(),
                        name,
                        notes,
                    });
                }
            }
        }
        list
    }

    pub fn save_admins(install_path: &Path, identity: &str, admins: &[AdminUser]) -> Result<()> {
        let path = Self::get_users_cfg_path(install_path, identity);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        let mut file = File::create(&path)?;
        writeln!(file, "// Rust Dedicated Server Admin Users (users.cfg)")?;
        writeln!(file, "// Generated by Epic Rust\n")?;

        for admin in admins {
            let cmd = if admin.role.to_lowercase() == "owner" {
                "ownerid"
            } else {
                "moderatorid"
            };
            if admin.notes.trim().is_empty() {
                writeln!(file, "{} {} \"{}\"", cmd, admin.steam_id, admin.name)?;
            } else {
                writeln!(
                    file,
                    "{} {} \"{}\" \"{}\"",
                    cmd, admin.steam_id, admin.name, admin.notes
                )?;
            }
        }

        Ok(())
    }

    pub fn add_admin(
        install_path: &Path,
        identity: &str,
        steam_id: &str,
        role: &str,
        name: &str,
        notes: &str,
    ) -> Result<Vec<AdminUser>> {
        let clean_id = steam_id.trim().trim_matches('"').trim();
        if clean_id.len() != 17 || !clean_id.chars().all(|c| c.is_ascii_digit()) {
            return Err(LauncherError::ArgumentError(
                "Invalid SteamID64: Must be a 17-digit number starting with 7656119...".into(),
            ));
        }

        let mut admins = Self::load_admins(install_path, identity);
        admins.retain(|a| a.steam_id != clean_id);

        admins.push(AdminUser {
            steam_id: clean_id.to_string(),
            role: if role.to_lowercase() == "owner" { "owner".into() } else { "moderator".into() },
            name: if name.trim().is_empty() { "Server Owner".into() } else { name.trim().into() },
            notes: notes.trim().into(),
        });

        Self::save_admins(install_path, identity, &admins)?;
        Ok(admins)
    }

    pub fn remove_admin(install_path: &Path, identity: &str, steam_id: &str) -> Result<Vec<AdminUser>> {
        let clean_id = steam_id.trim().trim_matches('"').trim();
        let mut admins = Self::load_admins(install_path, identity);
        admins.retain(|a| a.steam_id != clean_id);
        Self::save_admins(install_path, identity, &admins)?;
        Ok(admins)
    }

    fn tokenize_cfg_line(line: &str) -> Vec<String> {
        let mut tokens = Vec::new();
        let mut current = String::new();
        let mut in_quotes = false;

        for ch in line.chars() {
            match ch {
                '"' => in_quotes = !in_quotes,
                ' ' | '\t' if !in_quotes => {
                    if !current.is_empty() {
                        tokens.push(current.clone());
                        current.clear();
                    }
                }
                _ => current.push(ch),
            }
        }
        if !current.is_empty() {
            tokens.push(current);
        }
        tokens
    }
}
